modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="adventure_mod_"
version="1.0.0"
displayName="Adventure Mod 1.15.2"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="petil, MCreator"

[[dependencies.adventure_mod_]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




